import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { Avatar, Pagination } from '@nextui-org/react'

const CustomCheckbox = dynamic(() => import('../components/Checkbox'))
const CustomTable = dynamic(() => import('../components/Table'))
const CustomCollapse = dynamic(() => import('../components/Collapse'))

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextUI Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          brain swap
        </h1>
        <h3>the evolution of human philosophy is the evolution of AI philosophy</h3>
        {/* pagination */}
        <h2>your brain</h2>
        <h2>explore swaps</h2>
        <Pagination total={20} initialPage={1} />
        <h2>create a swap</h2>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          copyright 2023 by brain swap
        </a>
      </footer>
    </div>
  )
}
